export const CALENDAR_KEYS = {
  COURSE_OFFERING_TIMETABLE: "COURSE_OFFERING_TIMETABLE",
  ENROLLMENT: "ENROLLMENT",
  LATE_ENROLLMENT: "LATE_ENROLLMENT",
  COMMENCEMENT_GRADUATE: "COMMENCEMENT_GRADUATE",
  COMMENCEMENT_UNDERGRADUATE: "COMMENCEMENT_UNDERGRADUATE",
  ERP_ATTENDANCE_OPEN: "ERP_ATTENDANCE_OPEN",
};

export const CALENDAR_KEY_LABELS = {
  COURSE_OFFERING_TIMETABLE: "Course offering + timetable by department",
  ENROLLMENT: "Enrollment by student on portal",
  LATE_ENROLLMENT: "Late enrollment on portal",
  COMMENCEMENT_GRADUATE: "Commencement of graduate classes",
  COMMENCEMENT_UNDERGRADUATE: "Commencement of undergraduate classes",
  ERP_ATTENDANCE_OPEN: "Opening of ERP portal for attendance",
};